// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace MyWebApi.Domain.Entities;

public partial class Booking
{
    public int BookingID { get; set; }

    public int? GuestID { get; set; }

    public int? RoomNumber { get; set; }

    public DateOnly? CheckinDate { get; set; }

    public DateOnly? CheckoutDate { get; set; }

    public decimal? TotalPrice { get; set; }
}