// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace MyWebApi.Domain.Entities;

public partial class Event
{
    public int EventID { get; set; }

    public string? EventType { get; set; }

    public string? EventDescription { get; set; }

    public DateTime? EventDateTime { get; set; }
}