// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using MyWebApi.Application.Common.Interfaces;
using MyWebApi.Infrastructure.Data.Configurations;
using System;
using System.Collections.Generic;
using System.Reflection;
#nullable enable

namespace MyWebApi.Infrastructure.Data;

public partial class THUCHANHNET8_DAFContext : DbContext,IApplicationDbContext
{
    public THUCHANHNET8_DAFContext(DbContextOptions<THUCHANHNET8_DAFContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Booking> Bookings { get; set; }

    public virtual DbSet<Event> Events { get; set; }

    public virtual DbSet<Guest> Guests { get; set; }

    public virtual DbSet<Hotel> Hotels { get; set; }

    public virtual DbSet<Payment> Payments { get; set; }

    public virtual DbSet<Room> Rooms { get; set; }

    public virtual DbSet<RoomType> RoomTypes { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.ApplyConfigurationsFromAssembly(Assembly.GetExecutingAssembly());
      
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
